//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformesTecnicosPPV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Informes()
        {
            this.TipoInforme = new HashSet<TipoInforme>();
        }
    
        public int Id { get; set; }
        public string NombreInforme { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public byte[] Manual { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public int IdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoInforme> TipoInforme { get; set; }
    }
}
